name: Bump Version and Tag

on:
  push:
    branches:
      - develop

jobs:
  version-bump:
    runs-on: ubuntu-latest

    permissions:
      # Give the default GITHUB_TOKEN write permission to commit and push the
      # added or changed files to the repository.
      contents: write

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Bump version
      id: version
      env:
        GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
      run: |
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'

        # Get the latest tag
        echo git branch
        latest_tag=$(git describe --tags --abbrev=0 --match *.*.*)
        echo "Latest tag: $latest_tag"

        # Parse the latest version
        if [[ $latest_tag =~ ^v?([0-9]+)\.([0-9]+)\.([0-9]+)$ ]]; then
          major=${BASH_REMATCH[1]}
          minor=${BASH_REMATCH[2]}
          patch=${BASH_REMATCH[3]}
        else
          echo "No tags found or invalid tag format. Defaulting to 0.0.0"
          major=0
          minor=0
          patch=0
        fi

        # Increment the patch version
        new_patch=$((patch + 1))
        new_version="$major.$minor.$new_patch"
        echo "New version: $new_version"

        # Add tag
        git tag "$new_version"
        git push origin develop --tags