name: Bump Version and Tag

on:
  push:
    branches:
      - develop

jobs:
  version-bump:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: '8.0.x'

    - name: Bump version, create tag, and push changes
      id: version
      run: |
        # Extract the current version from the project file
        current_version=$(grep -oP '(?<=<Version>).*?(?=</Version>)' TestSerilog.csproj)
        echo "Current version: $current_version"

        # Increment the patch version
        IFS='.' read -r -a version_parts <<< "$current_version"
        version_parts[2]=$((version_parts[2] + 1))
        new_version="${version_parts[0]}.${version_parts[1]}.${version_parts[2]}"
        echo "New version: $new_version"

        # Update the project file with the new version
        sed -i "s/<Version>.*<\/Version>/<Version>$new_version<\/Version>/" TestSerilog.csproj

        # Commit the version bump and create a new tag
        git config --global user.name 'github-actions'
        git config --global user.email 'github-actions@github.com'
        git commit -am "Bump version to $new_version"
        git tag "$new_version"
        git push origin develop --tags
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
